config/routes.rb
Rails.application.routes.draw do
 
  
  get 'unterprodukts/stuecklist'

  get 'produkts/istwert'
  
  get 'auftrags/warenkorb'
  
  get 'produkts/adding_to_warenkorb'
  
  get 'produkts/delete_from_warenkorb'
  
  get 'auftrags/bestell_bestaetigung'
  
  get 'auftrags/bestellung_abschicken'
  
  get 'assoziationsanalyse/index'
  
  
  
  resources :unterprodukts

  resources :auftrags

  resources :kundes

  resources :produkts
  
  resources :assoziationsanalyse
  
  
  

  get 'search' => 'produkts#search'
  
  get 'assoziation' => 'assoziationsanalyse#index'
  
  

  root 'produkts#index'

end

app/models/kunde.rb
class Kunde < ActiveRecord::Base
  
  has_many:auftrag
  has_many:produtks, :through => :auftrag
  
end

app/controllers/kundes_controller.rb
class KundesController < ApplicationController
  before_action :set_kunde, only: [:show, :edit, :update, :destroy]

  # GET /kundes
  # GET /kundes.json
  def index
    @kundes = Kunde.all
  end

  # GET /kundes/1
  # GET /kundes/1.json
  def show
  end

  # GET /kundes/new
  def new
    @kunde = Kunde.new
  end

  # GET /kundes/1/edit
  def edit
  end

  # POST /kundes
  # POST /kundes.json
  def create
    @kunde = Kunde.new(kunde_params)

    respond_to do |format|
      if @kunde.save
        format.html { redirect_to @kunde, notice: 'Kunde was successfully created.' }
        format.json { render :show, status: :created, location: @kunde }
      else
        format.html { render :new }
        format.json { render json: @kunde.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kundes/1
  # PATCH/PUT /kundes/1.json
  def update
    respond_to do |format|
      if @kunde.update(kunde_params)
        format.html { redirect_to @kunde, notice: 'Kunde was successfully updated.' }
        format.json { render :show, status: :ok, location: @kunde }
      else
        format.html { render :edit }
        format.json { render json: @kunde.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kundes/1
  # DELETE /kundes/1.json
  def destroy
    @kunde.destroy
    respond_to do |format|
      format.html { redirect_to kundes_url, notice: 'Kunde was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kunde
      @kunde = Kunde.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kunde_params
      params.require(:kunde).permit(:vorname, :nachname, :email, :strasse, :hausnummer, :plz, :tel, :rolle)
    end
end

app/helpers/kundes_helper.rb
module KundesHelper
end

app/views/kundes/_form.html.erb
<%= form_for(@kunde) do |f| %>
  <% if @kunde.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kunde.errors.count, "error") %> prohibited this kunde from being saved:</h2>

      <ul>
      <% @kunde.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vorname %><br>
    <%= f.text_field :vorname %>
  </div>
  <div class="field">
    <%= f.label :nachname %><br>
    <%= f.text_field :nachname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :strasse %><br>
    <%= f.text_field :strasse %>
  </div>
  <div class="field">
    <%= f.label :hausnummer %><br>
    <%= f.text_field :hausnummer %>
  </div>
  <div class="field">
    <%= f.label :plz %><br>
    <%= f.text_field :plz %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
<div class="field">
    <%= f.label :rolle %><br>
    <%= f.text_field :rolle %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kundes/edit.html.erb
<h1>Kunde hinzufuegen</h1>

<%= render 'form' %>

<%= link_to 'Show', @kunde %> |
<%= link_to 'Back', kundes_path %>

app/views/kundes/index.html.erb
<h1>Kunden Liste</h1>

<table>
  <thead>
    <tr>
      <th>Vorname</th>
      <th>Nachname</th>
      <th>Email</th>
      <th>Strasse</th>
      <th>Hausnummer</th>
      <th>Plz</th>
      <th>Tel</th>
       <th>Rolle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kundes.each do |kunde| %>
      <tr>
        <td><%= kunde.vorname %></td>
        <td><%= kunde.nachname %></td>
        <td><%= kunde.email %></td>
        <td><%= kunde.strasse %></td>
        <td><%= kunde.hausnummer %></td>
        <td><%= kunde.plz %></td>
        <td><%= kunde.tel %></td>
        <td><%= kunde.rolle %></td>
        <td><%= link_to 'Show', kunde %></td>
        <td><%= link_to 'Edit', edit_kunde_path(kunde) %></td>
        <td><%= link_to 'Destroy', kunde, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kunde', new_kunde_path %>

app/views/kundes/new.html.erb
<h1>Neuer Kunde</h1>

<%= render 'form' %>

<%= link_to 'Back', kundes_path %>

app/views/kundes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vorname:</strong>
  <%= @kunde.vorname %>
</p>

<p>
  <strong>Nachname:</strong>
  <%= @kunde.nachname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @kunde.email %>
</p>

<p>
  <strong>Strasse:</strong>
  <%= @kunde.strasse %>
</p>

<p>
  <strong>Hausnummer:</strong>
  <%= @kunde.hausnummer %>
</p>

<p>
  <strong>Plz:</strong>
  <%= @kunde.plz %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @kunde.tel %>
</p>

<p>
  <strong>Rolle:</strong>
  <%= @kunde.rolle %>
</p>

<%= link_to 'Edit', edit_kunde_path(@kunde) %> |
<%= link_to 'Back', kundes_path %>