config/routes.rb
Rails.application.routes.draw do
 
  
  get 'unterprodukts/stuecklist'

  get 'produkts/istwert'
  
  get 'auftrags/warenkorb'
  
  get 'produkts/adding_to_warenkorb'
  
  get 'produkts/delete_from_warenkorb'
  
  get 'auftrags/bestell_bestaetigung'
  
  get 'auftrags/bestellung_abschicken'
  
  get 'assoziationsanalyse/index'
  
  
  
  resources :unterprodukts

  resources :auftrags

  resources :kundes

  resources :produkts
  
  resources :assoziationsanalyse
  
  
  

  get 'search' => 'produkts#search'
  
  get 'assoziation' => 'assoziationsanalyse#index'
  
  

  root 'produkts#index'

end

app/models/produkt.rb
require 'paperclip/media_type_spoof_detector'

class Array

   def array?() true end

   def seq?() true end

   def prepend(obj) [obj] + self end

   def rest()
     if(self.length != 0)
       self[1..(self.size - 1)]
     end
   end

end 

module Paperclip
 class MediaTypeSpoofDetector
 def spoofed?
 false
 end
 end
end

class Produkt < ActiveRecord::Base

  has_many :auftrag_fuer_produkts
  has_many :auftrags, through: :auftrag_fuer_produkts

  has_many:kunde, :through => :auftrags
  
  has_many :oberprodukte, :class_name => 'Unterprodukt', :foreign_key => 'oberprodukt_id'
  has_many :unterprodukte, :class_name => 'Unterprodukt', :foreign_key => 'unterprodukt_id'
 
  protected
  def self.search(query)
    where("name LIKE (?)", "%#{query}%")
  end
  
  public
  def self.get_oberprodukt()
    where(:kategorie => 'A')
  end
  
  public
  def self.get_auftrag(id)
    where(:produkt_id => "%#{id}%")
  end
  
  def self.produkt_aus_id(id) 
      #SELECT * FROM `produkts` WHERE `id` = 1;
      where( "`id` = ?" , id)
           
  end 
  
#  public
#  def self.sum_of_stueckzahl(p_id, date)
#    sum(:stueckzahl, :condition => ["produkt_id= ? AND datum LIKE (?)",
#                                    p_id, "%#{date}%"])
#  end
  

#  def show_stuecklist()
#     where("oberprodukt_id LIKE (?)", "%#{self}%")
#  end
  
  has_attached_file :bild, :styles => { :small => "150x150>" },
 :url => "/assets/produkts/:id/:style/:basename.:extension",
 :path => ":rails_root/public/assets/produkts/:id/:style/:basename.:extension"

   #validates_attachment_presence :bild
   validates_attachment_size :bild, :less_than => 5.megabytes
   validates_attachment_content_type :bild, :content_type => ['image/jpeg', 'image/png']
   has_attached_file :bild, :styles => { :medium => "150x150>", :thumb => "100x100>" }


end

app/controllers/produkts_controller.rb
class ProduktsController < ApplicationController
  before_action :set_produkt, only: [:show, :edit, :update, :destroy]
  $array =  []

  # GET /produkts
  # GET /produkts.json
  def index
    @produkts = Produkt.all
  end

  # GET /produkts/1
  # GET /produkts/1.json
  def show
  end

  # GET /produkts/new
  def new
    @produkt = Produkt.new
  end

  # GET /produkts/1/edit
  def edit
  end
  
   # GET /auftrags/istWert
  def istwert
    @produkt = Produkt.all
    render "istwert"
  end
  
  
  def adding_to_warenkorb
    add_to_warenkorb(params[:produkt_id]|| params[:id])
    
   
  end
  
  def delete_from_warenkorb
     delete_warenkorb(params[:produkt_id]|| params[:id])
    
  end
  
  # POST /produkts
  # POST /produkts.json
  def create
    @produkt = Produkt.new(produkt_params)

    respond_to do |format|
      if @produkt.save
        format.html { redirect_to @produkt, notice: 'Produkt was successfully created.' }
        format.json { render :show, status: :created, location: @produkt }
      else
        format.html { render :new }
        format.json { render json: @produkt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produkts/1
  # PATCH/PUT /produkts/1.json
  def update
    respond_to do |format|
      if @produkt.update(produkt_params)
        format.html { redirect_to @produkt, notice: 'Produkt was successfully updated.' }
        format.json { render :show, status: :ok, location: @produkt }
      else
        format.html { render :edit }
        format.json { render json: @produkt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produkts/1
  # DELETE /produkts/1.json
  def destroy
    @produkt.destroy
    respond_to do |format|
      format.html { redirect_to produkts_url, notice: 'Produkt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def search
    @produkts = Produkt.search(params[:suchbegriff])
     render "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produkt
      @produkt = Produkt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produkt_params
      params.require(:produkt).permit(:name, :kategorie, :beschreibung, :preis, :gueltigVon, :gueltigBis, :bild)
    end
end

app/helpers/produkts_helper.rb
module ProduktsHelper
end

app/views/produkts/_form.html.erb
<%= form_for @produkt, :html => { :multipart => true } do |f| %>
  <% if @produkt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produkt.errors.count, "error") %> prohibited this produkt from being saved:</h2>
      
      <ul>
        <% @produkt.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kategorie %><br>
    <%= f.text_field :kategorie %>
  </div>
  <div class="field">
    <%= f.label :beschreibung %><br>
    <%= f.text_field :beschreibung %>
  </div>
  <div class="field">
    <%= f.label :preis %><br>
    <%= f.number_field :preis %>
  </div>
  <div class="field">
    <%= f.label :gueltigVon %><br>
    <%= f.date_select :gueltigVon %>
  </div>
  <div class="field">
    <%= f.label :gueltigBis %><br>
    <%= f.date_select :gueltigBis %>
  </div>
  <div class="actions">
    <%= f.file_field :bild %>
    <%= f.submit %>
  </div>
<% end %>

app/views/produkts/adding_to_warenkorb.html.erb
<br><br>
<h2>Hinzugefügt</h2>

<p>Das ausgewählte Produkt wurde erfolgreich in den Warenkorb gelegt.
   <br> Um ihren Warenkorb anzusehen klicken sie hier </p>

<a href="/auftrags/warenkorb" style="font-weight:bold; color:purple">Zum Warenkorb</a><br>
    

app/views/produkts/delete_from_warenkorb.html.erb
<br><br>
<h2>Entfernt</h2>

<p>Das ausgewählte Produkt wurde erfolgreich aus dem Warenkorb entfernt.
   <br> Um ihren Warenkorb anzusehen klicken sie hier </p>

<a href="/auftrags/warenkorb" style="font-weight:bold; color:purple">Zum Warenkorb</a><br>
    

app/views/produkts/edit.html.erb
<h1>Editing produkt</h1>

<%= form_for @produkt, :url => produkts_path, :html => { :multipart => true } do |form| %>
    <%= form.file_field :bild %>
  <% end %>

<%= render 'form' %>

<%= link_to 'Show', @produkt %> |
<%= link_to 'Back', produkts_path %>

app/views/produkts/index.html.erb
<br>
<h2 style="font-weight:bold; color:purple">Produktliste</h2><br>

<table id="produktliste">
  <thead>
    <tr>
      <th>Bild</th>
      <th>Name</th>
      <th>Beschreibung</th>
      <th>Preis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produkts.each do |produkt| %>
      <tr>
        <%  if Kunde.where(:email => selected).first.rolle == 2%>
        <td><%= link_to(image_tag(produkt.bild.url(:medium)), produkt) %></td>
        <td><%= produkt.name %></td>
        <td><%= produkt.beschreibung %></td>
        <td><%= produkt.preis %></td>
        <td><%= link_to 'Produkt anzeigen', produkt %></td>
         <% else  %>
        <td><%= link_to(image_tag(produkt.bild.url(:medium)), produkt) %></td>
        <td><%= produkt.name %></td>
        <td><%= produkt.beschreibung %></td>
        <td><%= produkt.preis %></td>
        <td><%= link_to 'Show', produkt %></td>
        <td><%= link_to 'Edit', edit_produkt_path(produkt) %></td>
        <td><%= link_to 'Destroy', produkt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neues Produkt', new_produkt_path %>

app/views/produkts/istwert.html.erb
<br>
<h2 style="font-weight:bold; color:purple">2014</h2><br>
<h2 style="font-weight:bold; color:purple">Ist-Wert</h2>

 <table id="istwerttabelle">
      <tr>
          <th style="width:150px;"> Produkt </th>
          
            <% array = [1,2,3,4,5,6,7,8,9,10,11,12] 
               array.each do |month| %>
          
          <th style="width:150px;"><%= month %></th>
            <% end %>
          
      </tr>
    <% @produkt.each do |produkt| %>
      <tr>
          <td><%= produkt.name %></td>
          
          <% 

             def sum_of_stueckzahl(p_id, date, year)
              if((1..9).include?(date))
                auftraege = Auftrag.where("datum Like '#{year}-0#{date}-%'")
              elsif((10..12).include?(date))
                auftraege = Auftrag.where("datum Like '#{year}-#{date}-%'")
              end
            
              auftrags_id_array = []
              auftraege.each{|elem| auftrags_id_array << elem.id}
              AuftragFuerProdukt.where("auftrag_id IN (?) AND produkt_id = ?", auftrags_id_array, p_id ).sum :stueckzahl
              #SELECT id FROM `auftrags` WHERE datum LIKE "2014-11-%";
              #SELECT SUM(stueckzahl) FROM `auftrag_fuer_produkts` WHERE auftrag_id IN ##auftrags_id_array AND produkt_id= ##p_id;
            end
            
            
            def miau_(p_id, monat, year, accu)
                 monat_first = monat.first.to_i
              if(monat.length == 0 or accu > 12)
                return
              elsif(monat.length == 1 and monat_first == accu)
                stueckzahl = sum_of_stueckzahl(p_id, monat_first, year)
                %>
                  <td align="center"><%= stueckzahl %></td>
                <%
              elsif(monat_first == accu)
                stueckzahl = sum_of_stueckzahl(p_id, monat_first, year)
                %>
                  <td align="center"><%= stueckzahl %></td>
                <%
                miau_(p_id, monat.rest, year, accu+1) 
              elsif(accu <= 12) 
                accu1 = accu +1
                %>
                  <td align="center">0</td>
                <%

                miau_(p_id, monat, year, accu1)
              end
            end
           
            def miau(p_id, monat, year)
              miau_(p_id, monat, year, 1)
            end
           
            produktID = produkt.id 
            monats_array = produkt.auftrags.map{|auftrag|  auftrag.datum.strftime("%-m")}
            
             
            # Array zu Set um dublikate zu entfernen und Set zu Array
            sortiertes_array = monats_array.sort
            set_array = sortiertes_array.to_set
            array = set_array.to_a 
             
            miau(produktID.to_i, array, 2014)
            
            %>
      </tr>
           
    <% end %>
  </table>




<br><br><br>




<h2 style="font-weight:bold; color:purple">Planwert</h2>

<table id="planwerttabelle">
    <tr>
          <th style="width:150px;"> Produkt </th>
          
            <% array = [1,2,3,4,5,6,7,8,9,10,11,12] 
               array.each do |month| %>
          
          <th style="width:150px;"><%= month %></th>
            <% end %>
          
      </tr>
      
      <% @produkt.each do |produkt| %>
      <tr>
          <td><%= produkt.name %></td>
          
          
          <%
          #Berechnung des Vormonats
          #monat: Monat als Integer
          def vormonat(monat)
            range = (1..12)
            if(range.include?(monat))              
              if (monat == 1)
                12
              else
                monat-1
              end
            end
          end
         
          
          #Funktion zur Breechnung der Planungstabelle
          #p_id: Produkt ID die zu dem jeweiligen Produkt gehört
          #faktor: Glättungsfaktor muss zwischen 0.1 und 0.3 liegen
          #monat: Monat als Integer zu dem eine Primärbedarfsanalyse 
                 #durchgeführt werden soll
          def planungstabelle(p_id, faktor, monat, year)
              #letzter Monat
              dritter_monat = vormonat(monat)
              #vorletzter Monat
              zweiter_monat = vormonat(dritter_monat)
              #vorvorletzter Monat
              erster_monat = vormonat(zweiter_monat)
              
            if((1..3).include?(monat))

              stueckzahl_dritter_monat = sum_of_stueckzahl(p_id, dritter_monat, year-1)
              stueckzahl_zweiter_monat = sum_of_stueckzahl(p_id, zweiter_monat, year-1)
              stueckzahl_erster_monat = sum_of_stueckzahl(p_id, erster_monat, year-1)

            else

              stueckzahl_dritter_monat = sum_of_stueckzahl(p_id, dritter_monat, year)
              stueckzahl_zweiter_monat = sum_of_stueckzahl(p_id, zweiter_monat, year)
              stueckzahl_erster_monat = sum_of_stueckzahl(p_id, erster_monat, year)

            end
              durchschnitt = (stueckzahl_dritter_monat + stueckzahl_zweiter_monat + stueckzahl_erster_monat)/3.to_f

              exponentielle_glaettung = durchschnitt + faktor*(stueckzahl_dritter_monat - durchschnitt)
              %>
                  <td align="center"><%= exponentielle_glaettung.round(2) %></td>
              <% 
          end
          
          %>
          
          
          
          
          <% a = [1,2,3,4,5,6,7,8,9,10,11,12] 
             a.each do |zahl| 
               
             produkt_id = produkt.id  
             
             planungstabelle(produkt_id, 0.2, zahl, 2014)
          %>
            
          <% end %>
      </tr>
      <% end %>
</table>





<br><br><br><br>
<h2 style="font-weight:bold; color:purple">2015</h2><br>
<h2 style="font-weight:bold; color:purple">Ist-Wert</h2>

 <table id="istwerttabelle">
      <tr>
          <th style="width:150px;"> Produkt </th>
          
            <% array = [1,2,3,4,5,6,7,8,9,10,11,12] 
               array.each do |month| %>
          
          <th style="width:150px;"><%= month %></th>
            <% end %>
          
      </tr>
    <% @produkt.each do |produkt| %>
      <tr>
          <td><%= produkt.name %></td>
          
          <% 
           
            produktID = produkt.id 
            monats_array = produkt.auftrags.map{|auftrag|  auftrag.datum.strftime("%-m")}
            
             
            # Array zu Set um dublikate zu entfernen und Set zu Array
            sortiertes_array = monats_array.sort
            set_array = sortiertes_array.to_set
            array = set_array.to_a 
            miau(produktID.to_i, array, 2015)
            
            %>
      </tr>
           
    <% end %>
  </table>




<br><br><br>



<h2 style="font-weight:bold; color:purple">Planwert</h2>

<table id="planwerttabelle">
    <tr>
          <th style="width:150px;"> Produkt </th>
          
            <% array = [1,2,3,4,5,6,7,8,9,10,11,12] 
               array.each do |month| %>
          
          <th style="width:150px;"><%= month %></th>
            <% end %>
          
      </tr>
      
      <% @produkt.each do |produkt| %>
      <tr>
          <td><%= produkt.name %></td>
          
          
          <% a = [1,2,3,4,5,6,7,8,9,10,11,12] 
             a.each do |zahl| 
               
             produkt_id = produkt.id  
             
             planungstabelle(produkt_id, 0.2, zahl, 2015)
          %>
            
          <% end %>
      </tr>
      <% end %>
</table>

app/views/produkts/new.html.erb
<h1>Neues Produkt</h1>

<%= render 'form' %>

<%= link_to 'Back', produkts_path %>

app/views/produkts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @produkt.name %>
</p>

<p>
  <strong>Kategorie:</strong>
  <%= @produkt.kategorie %>
</p>

<p>
  <strong>Beschreibung:</strong>
  <%= @produkt.beschreibung %>
</p>

<p>
  <strong>Preis:</strong>
  <%= @produkt.preis %>
</p>

<p>
  <strong>Gueltigvon:</strong>
  <%= @produkt.gueltigVon %>
</p>

<p>
  <strong>Gueltigbis:</strong>
  <%= @produkt.gueltigBis %>
</p>

<%= image_tag @produkt.bild.url(:medium) %>
<%  if Kunde.where(:email => session[:user_session]).first.rolle == 1%>
<%= link_to 'Edit', edit_produkt_path(@produkt) %> |
<%= link_to 'Zurück', produkts_path %> |
<%= link_to 'In den Warenkob', controller: "produkts", action: "adding_to_warenkorb", id: @produkt%>
<%else %>
<%= link_to 'Zurück', produkts_path %> |
<%= link_to 'In den Warenkob', controller: "produkts", action: "adding_to_warenkorb", id: @produkt%>
<%end%>