config/routes.rb
Rails.application.routes.draw do
 
  
  get 'unterprodukts/stuecklist'

  get 'produkts/istwert'
  
  get 'auftrags/warenkorb'
  
  get 'produkts/adding_to_warenkorb'
  
  get 'produkts/delete_from_warenkorb'
  
  get 'auftrags/bestell_bestaetigung'
  
  get 'auftrags/bestellung_abschicken'
  
  get 'assoziationsanalyse/index'
  
  
  
  resources :unterprodukts

  resources :auftrags

  resources :kundes

  resources :produkts
  
  resources :assoziationsanalyse
  
  
  

  get 'search' => 'produkts#search'
  
  get 'assoziation' => 'assoziationsanalyse#index'
  
  

  root 'produkts#index'

end

app/models/auftrag.rb
class Auftrag < ActiveRecord::Base

  has_many :auftrag_fuer_produkts
  has_many :produkts, through: :auftrag_fuer_produkts
  belongs_to:kunde

  
end

app/controllers/auftrags_controller.rb
class AuftragsController < ApplicationController
  before_action :set_auftrag, only: [:show, :edit, :update, :destroy]
  before_filter :warenkorb
  $array =  []

  # GET /auftrags
  # GET /auftrags.json
  def index
    @auftrags = Auftrag.all
  end

  # GET /auftrags/1
  # GET /auftrags/1.json
  def show
  end

  # GET /auftrags/new
  def new
    @auftrag = Auftrag.new
  end

  # GET /auftrags/1/edit
  def edit
  end

  def warenkorb
    
  end
  
  
  # POST /auftrags
  # POST /auftrags.json
  def create
    @auftrag = Auftrag.new(auftrag_params)

    respond_to do |format|
      if @auftrag.save
        format.html { redirect_to @auftrag, notice: 'Auftrag was successfully created.' }
        format.json { render :show, status: :created, location: @auftrag }
      else
        format.html { render :new }
        format.json { render json: @auftrag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auftrags/1
  # PATCH/PUT /auftrags/1.json
  def update
    respond_to do |format|
      if @auftrag.update(auftrag_params)
        format.html { redirect_to @auftrag, notice: 'Auftrag was successfully updated.' }
        format.json { render :show, status: :ok, location: @auftrag }
      else
        format.html { render :edit }
        format.json { render json: @auftrag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auftrags/1
  # DELETE /auftrags/1.json
  def destroy
    @auftrag.destroy
    respond_to do |format|
      format.html { redirect_to auftrags_url, notice: 'Auftrag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
    def bestellung_abschicken
      
      datum = Time.now.strftime("%Y-%m-%d")
      produkte = $array
      kunden_id = Kunde.where(:email => session[:user_session]).first.id
      Auftrag.create(datum: datum, kunden_id: kunden_id)
      
      auftrag = Auftrag.where("datum ='#{datum}' and kunden_id =#{kunden_id}")
      auftrag_id = auftrag.first.id
 
      while (!produkte.empty?)
        a = produkte.first
        accu = produkte.count(a)
        AuftragFuerProdukt.create(auftrag_id: auftrag_id, produkt_id: a , stueckzahl: accu)
        produkte.delete(a)
        
      end
      
     $array = []
     session[:warenkorb_produkt] = $array
    end
    
    def bestell_bestaetigung
      
      
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auftrag
      @auftrag = Auftrag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auftrag_params
      params.require(:auftrag).permit(:datum, :stueckzahl,:kunden_id, :produkt_id)
    end
    
      

end

app/helpers/auftrags_helper.rb
module AuftragsHelper
end

app/views/auftrags/_form.html.erb
<%= form_for(@auftrag) do |f| %>
  <% if @auftrag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auftrag.errors.count, "error") %> prohibited this auftrag from being saved:</h2>

      <ul>
      <% @auftrag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :datum %><br>
    <%= f.date_select :datum %>
  </div>
  <div class="field">
    <%= f.label :kunden_id %><br>
    <%= f.number_field :kunden_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auftrags/bestell_bestaetigung.html.erb
<h1>Prüfen und Bestellen</h1>
<h3> Produkte</h3>
  <table id="bestell_produktliste">
    <tr>
     <th style="width:150px;"> Bild </th>
     <th style="width:150px;"> Produkt </th>
     <th style="width:150px;"> Einzelpreis </th>
     <th style="width:150px;"> Stückzahl </th>
     <th style="width:150px;"> Preis </th>
    </tr>
    
    <%
    $id
    produkt_hash ={}
    get_warenkorb.each do |id| 
      if (!produkt_hash.has_key?(id))
        produkt_hash.store(id,1)
      else
        value = produkt_hash.values_at(id)
        first_value = value.first
        first_value += 1
        produkt_hash.store(id, first_value)
      end
    end
  
      produkt_hash.each do |key,value|
        
    %>
    <tr>
      <% 
    
       if $summe.nil?
         $summe = 0
       end
     
     
        produkte = Produkt.produkt_aus_id(key)
        erstes_produkt = produkte.first
       
      
        $summe += (erstes_produkt.preis * value)
        
        
      %>
        
      <td align="center"><%= image_tag erstes_produkt.bild.url(:medium) %></td>
      <td align="center"><%= erstes_produkt.name %></td>
      <td align="center"><%= erstes_produkt.preis %> Euro</td>
      <td align="center"><%= value %> </td>
      <td align="center"><%= erstes_produkt.preis * value %> Euro</td>
      <% 
       
      $id = key %>
    

      
      <%#*<td align="center"><%= text_field_tag(:anzahl, '', size: 10)%></td>
    </tr>
    <% end %>
    
</table>

 <h4 style="position:absolute;">Summe</h4>
<br><br><br>
<table id="summe"  border="1">
  <tr>
     <th style="width:80px;" align="center"><%= $summe %> Euro</th>
      
    </tr>
  
    <% 
      $summe = 0
    %>
</table>

<%kunde = Kunde.where(:email => session[:user_session]).first%>
<h3>Kundendaten</h3>
<table id="kundendaten">
<tr><th>Lieferadresse</th>
  <th>  Rechnungsadresse</th></tr>
<tr>
  <td>
<span><%=  kunde.vorname%></span><br>
<span><%=  kunde.nachname%></span><br>
<span><%=  kunde.strasse%></span>
<span><%=  kunde.hausnummer%></span><br>
<span><%=  kunde.plz%></span>
  </td>

  <td>
<span align="center"><%=  kunde.vorname%></span><br>
<span><%=  kunde.nachname%></span><br>
<span><%=  kunde.strasse%></span>
<span><%=  kunde.hausnummer%></span><br>
<span><%=  kunde.plz%></span>
</td>
</tr>
</table>

<h3>  Bezahlart</h3>
<p>Rechnung</p>

<h3><%= link_to 'Bestellung abschicken', controller: "auftrags", action: "bestellung_abschicken", id: $id%></h3>

app/views/auftrags/bestellung_abschicken.html.erb
<br><br>
<h2>Bestellung</h2>



<p>Die Bestellung wurde erfolgreich übermittelt.</p>
   <%#*<br> Um ihren Warenkorb anzusehen klicken sie hier </p>%>


<a href="/auftrags/warenkorb" style="font-weight:bold; color:purple">Zum Warenkorb</a><br>

app/views/auftrags/edit.html.erb
<h1>Editing auftrag</h1>

<%= render 'form' %>

<%= link_to 'Show', @auftrag %> |
<%= link_to 'Back', auftrags_path %>

app/views/auftrags/index.html.erb
<h1>Auftragsliste</h1>

<table>
  <thead>
    <tr>
      <th>Datum</th>
      <th>KundenID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auftrags.each do |auftrag| %>
      <tr>
        <td align="center"><%= auftrag.datum %></td>
        <td align="center"><%= auftrag.kunden_id %></td>
        <td><%= link_to 'Show', auftrag %></td>
        <td><%= link_to 'Edit', edit_auftrag_path(auftrag) %></td>
        <td><%= link_to 'Destroy', auftrag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auftrag', new_auftrag_path %>

app/views/auftrags/new.html.erb
<h1>New auftrag</h1>

<%= render 'form' %>

<%= link_to 'Back', auftrags_path %>

app/views/auftrags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datum:</strong>
  <%= @auftrag.datum %>
</p>

<p>
  <strong>KundenID:</strong>
  <%= @auftrag.kunden_id %>
</p>


<%= link_to 'Edit', edit_auftrag_path(@auftrag) %> |
<%= link_to 'Back', auftrags_path %>

app/views/auftrags/warenkorb.html.erb
<br>
<h2 style="font-weight:bold; color:purple">Warenkorb</h2>


    <% array = get_warenkorb
    if array.empty?
      %>
    <p>In ihrem Warenkorb befinden sich noch keine Artikel</p>
    <a href="/produkts" style="font-weight:bold; color:purple">Zu den Produkten</a><br>
    
    <%
    else
    %>
    
<table id="warenkorb">
    <tr>
     <th style="width:150px;"> Bild </th>
     <th style="width:150px;"> Produkt </th>
     <th style="width:150px;"> Preis </th>
      
    </tr>
    
    <%
    $id
    array.each do |id| %>
    <tr>
      <% 
       if $summe.nil?
         $summe = 0
       end
     
        produkte = Produkt.produkt_aus_id(id)
        erstes_produkt = produkte.first
       
      
        $summe += erstes_produkt.preis
      %>
        
      <td align="center"><%= image_tag erstes_produkt.bild.url(:medium) %></td>
      <td align="center"><%= erstes_produkt.name %></td>
      
      <td align="center"><%= erstes_produkt.preis %> Euro</td>
      <% $id = id %>
      <td align="center"><%= link_to 'Aus dem Warenkorb löschen', controller: "produkts", action: "delete_from_warenkorb", id: $id%></td>

      
      <%#*<td align="center"><%= text_field_tag(:anzahl, '', size: 10)%></td>
    </tr>
    <% end %>
    
</table>

<h3 style="position:absolute;">Summe</h3>
<br><br><br>
<table id="summe" style="position:absolute;" border="1">
  <tr>
     <th style="width:80px;" align="center"><%= $summe %> Euro</th>
      
    </tr>
  
    <% 
      $summe = 0
    %>
</table>
<br><br><br>
<h3 style="position:absolute;"><%= link_to 'Bestellen', controller: "auftrags", action: "bestell_bestaetigung", id: $id%></h3>

<table id="summe" style="position:absolute;" border="1">

<% end %>
<br><br><br>