config/routes.rb
Rails.application.routes.draw do
 
  
  get 'unterprodukts/stuecklist'

  get 'produkts/istwert'
  
  get 'auftrags/warenkorb'
  
  get 'produkts/adding_to_warenkorb'
  
  get 'produkts/delete_from_warenkorb'
  
  get 'auftrags/bestell_bestaetigung'
  
  get 'auftrags/bestellung_abschicken'
  
  get 'assoziationsanalyse/index'
  
  
  
  resources :unterprodukts

  resources :auftrags

  resources :kundes

  resources :produkts
  
  resources :assoziationsanalyse
  
  
  

  get 'search' => 'produkts#search'
  
  get 'assoziation' => 'assoziationsanalyse#index'
  
  

  root 'produkts#index'

end

app/models/unterprodukt.rb
class Unterprodukt < ActiveRecord::Base
  belongs_to :oberprodukt, :class_name => 'Produkt', :foreign_key => 'oberprodukt_id'
  belongs_to :unterprodukt, :class_name => 'Produkt', :foreign_key => 'unterprodukt_id'




  
 
end

app/controllers/unterprodukts_controller.rb
class UnterproduktsController < ApplicationController
  before_action :set_unterprodukt, only: [:show, :edit, :update, :destroy]

  # GET /unterprodukts
  # GET /unterprodukts.json
  def index
    @unterprodukts = Unterprodukt.all
  end

  # GET /unterprodukts/1
  # GET /unterprodukts/1.json
  def show
  end

  # GET /unterprodukts/new
  def new
    @unterprodukt = Unterprodukt.new
  end

  # GET /unterprodukts/1/edit
  def edit
  end
   
  
  def stuecklist
    @unterprodukt = Produkt.get_oberprodukt()
    render "stuecklist"
  end
  
  
  # POST /unterprodukts
  # POST /unterprodukts.json
  def create
    @unterprodukt = Unterprodukt.new(unterprodukt_params)

    respond_to do |format|
      if @unterprodukt.save
        format.html { redirect_to @unterprodukt, notice: 'Unterprodukt was successfully created.' }
        format.json { render :show, status: :created, location: @unterprodukt }
      else
        format.html { render :new }
        format.json { render json: @unterprodukt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unterprodukts/1
  # PATCH/PUT /unterprodukts/1.json
  def update
    respond_to do |format|
      if @unterprodukt.update(unterprodukt_params)
        format.html { redirect_to @unterprodukt, notice: 'Unterprodukt was successfully updated.' }
        format.json { render :show, status: :ok, location: @unterprodukt }
      else
        format.html { render :edit }
        format.json { render json: @unterprodukt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unterprodukts/1
  # DELETE /unterprodukts/1.json
  def destroy
    @unterprodukt.destroy
    respond_to do |format|
      format.html { redirect_to unterprodukts_url, notice: 'Unterprodukt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unterprodukt
      @unterprodukt = Unterprodukt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unterprodukt_params
      params.require(:unterprodukt).permit(:menge, :oberprodukt_id, :unterprodukt_id)
    end
    
   
    
   

end

app/helpers/unterprodukts_helper.rb
module UnterproduktsHelper
end

app/views/unterprodukts/_form.html.erb
<%= form_for(@unterprodukt) do |f| %>
  <% if @unterprodukt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unterprodukt.errors.count, "error") %> prohibited this unterprodukt from being saved:</h2>

      <ul>
      <% @unterprodukt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :menge %><br>
    <%= f.number_field :menge %>
  </div>
  <div class="field">
    <%= f.label :oberprodukt_id %><br>
    <%= f.number_field :oberprodukt_id %>
  </div>
  <div class="field">
    <%= f.label :unterprodukt_id %><br>
    <%= f.number_field :unterprodukt_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unterprodukts/edit.html.erb
<h1>Editing unterprodukt</h1>

<%= render 'form' %>

<%= link_to 'Show', @unterprodukt %> |
<%= link_to 'Back', unterprodukts_path %>

app/views/unterprodukts/index.html.erb
<h1 style="font-weight:bold; color:plum">Unterproduktliste</h1>

<table>
  <thead>
    <tr>
      <%#*<th>Oberprodukt</th>%>
      <%#*<th>Unterprodukt</th>%>
      <%#*<th>Menge</th>%>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unterprodukt.each do |unterprodukt| %>
      <tr>
        <%#*<td><%= unterprodukt.oberprodukt.name %></td>%>
        <%#*<td><%= unterprodukt.unterprodukt.name %></td>%>
        <%#*<td><%= unterprodukt.menge %></td>%>
        <td><%= unterprodukt.name %></td>
        <td><%= link_to 'Show', unterprodukt %></td>
        <td><%= link_to 'Edit', edit_unterprodukt_path(unterprodukt) %></td>
        <td><%= link_to 'Destroy', unterprodukt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Unterprodukt', new_unterprodukt_path %>

app/views/unterprodukts/new.html.erb
<h1>Neue Unterprodukte</h1>

<%= render 'form' %>

<%= link_to 'Back', unterprodukts_path %>

app/views/unterprodukts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Menge:</strong>
  <%= @unterprodukt.menge %>
</p>

<%= link_to 'Edit', edit_unterprodukt_path(@unterprodukt) %> |
<%= link_to 'Back', unterprodukts_path %>

app/views/unterprodukts/stuecklist.html.erb
<br>
<h2 style="font-weight:bold; color:purple">Unterproduktliste</h2>
 

<% def rec_produkt(entry, oberprodukt_menge, tiefe) %>
    <% entry.oberprodukte.each do |obj|  
      artikel = Produkt.find(obj.unterprodukt_id) %>
      <tr>
          <td class="tiefe<%= tiefe %>"><%= artikel.name %></td>
          <td><%= obj.menge * oberprodukt_menge %></td>
      </tr>
      <% rec_produkt(artikel, obj.menge, tiefe + 1)
    end %>
<% end %>

  <table id="stueckliste">
      <tr>
            <th style="width:280px;">Artikel</th>
            <th>Menge</th>
      </tr>
    <% @unterprodukt.each do |unterprodukt| %>
      <tr>
          <td><%= unterprodukt.name %></td>
          <td>1</td>
      </tr>
      <%  rec_produkt(unterprodukt, 1, 1) %>
           
    <% end %>
  </table>

<br>